### ISSUE TITLE
Can not find `alext.h` on macOS Sierra

### ISSUE THREAD

**Issue by karamellpelle** [kcat/alure#1]
I have macOS Sierra, newest XCode, and cmake 3.6.2. It fails during build since it can not find the file _alext.h_ included by _./src/device.h_. I can see that there is a file _./include/alext.h_. But `make -n` shows that only the folder _./include/AL_ is included (not _./include_ where __alext.h_ is).

[build.txt](https://github.com/kcat/alure/files/571232/build.txt)

**Comment by karamellpelle** [comment]
I think this is a problem with macOS. If I change the _./CMakeLists.txt:11_ (in order to include _./alext.h_, the one given by alure) to 

```
include_directories(${alure_SOURCE_DIR}/include/AL ${alure_SOURCE_DIR}/include ${alure_SOURCE_DIR}/src ${alure_BINARY_DIR} ${OPENAL_INCLUDE_DIR})
```

It gives me a new compile error:

```
/Users/karamellpelle/source/alure/src/device.h:48:5: error: unknown type name 'LPALCGETSTRINGISOFT'; did you mean 'LPALCGETSTRING'?
```

As I can see, `LPALCGETSTRINGISOFT` is defined in the **openal-soft** implementation of _alext.h_, but not in _./include/alext.h_. There is however no _alext.h_ in the macOS OpenAL implementation (_/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenAL.framework/Headers_)

With `brew` I can install openal-soft, but I have to include the headers myself; see 
[brew-openal-soft.txt](https://github.com/kcat/alure/files/571289/brew-openal-soft.txt)

**Comment by kcat** [comment]
Commit 87822c6f2ae88c4eba17f1e4d8f606e58c80b7e4 updates Alure's internal headers with a newer alext.h that has the missing function type, and commit b312f0d54791924f842cc3f15c8b79126ac195df re-enables use of the internal AL headers over the system headers. Does it work now?

**Comment by karamellpelle** [comment]
By pulling the newest [HEAD](https://github.com/kcat/alure/commit/ecb0f777882756f525a6eba17a10f1033d1ef0bb), everything compiles fine with a small modification: #3 

Thanks!
