### ISSUE TITLE
main.h is a very misleading name, and alure::Bitfield shouldn't be located in there

### ISSUE THREAD

**Issue by Cazadorro** [kcat/alure#11]
Looking for what the heck `DECL_THUNK0->3` are, found it was defined in main.h for some reason.  For some reason main.h also has `alure::Bitfield`, definition inside of it. not sure why this is here, but I can make a pull request if I've got the time to fix this, its really confusing looking at the source code and trying to remember "oh bitfields is in ... main.h?"

**Comment by kcat** [comment]
I suppose ```main.h``` would be better named ```misc.h```. Since ```Bitfield``` is so small and not something to be made public, I didn't feel it was worth making a whole new header just for it. But maybe I should. Most IDEs should be able to tell you where things are declared or defined, though.

**Comment by Cazadorro** [comment]
I split up the header and built to make sure it works.  After I fix the readme stuff you talked about I'll make a pull request.   Note no functional changes should have taken place, I didn't actually edit the functions and definitions themselves, just moved where they were located and changed main.h to be something that makes more sense given the refactor.
