### ISSUE TITLE
"Called context is not current" exception

### ISSUE THREAD

**Issue by karamellpelle** [kcat/alure#19]
[The newest Alure works](https://github.com/kcat/alure/issues/5): It builds and the examples run well.

I pulled [the latest Alure](https://github.com/kcat/alure/commit/e8ae3d3d134c12c9b6aace5e07885807f0bf6024) into [my project](https://github.com/karamellpelle/open-forest). I had to do some minor modifications in my code to adapt to the newer Alure API, in particular using PIMPL objects in favor of pointers, and now everything compiles.

However, my program gets killed by Alure: Alure throws "Called context is not current" exception(s). They seems to come from `void CheckContext(const ContextImpl *ctx)`/`void CheckContext(const ContextImpl &ctx)`. I don't know why this happens. Your examples work well. It may have something to do with threads in my program that I am not aware of.

Do @kcat have some suggestions of what causes this error in my program?

Thank you for this great OpenAL library! 🚁

**Comment by kcat** [comment]
> However, my program gets killed by Alure: Alure throws "Called context is not current" exception(s). They seems to come from void CheckContext(const ContextImpl *ctx)/void CheckContext(const ContextImpl &ctx). I don't know why this happens.

That generally means you forgot to call `alure::Context::MakeCurrent`. One other possibility, since you mentioned updating Alure to the newer pImpl-based API, check that you held on to the `DeviceManager` after setting up the device and context. With the new interface, if that goes out of scope and gets destroyed, everything shuts down automatically.

**Comment by karamellpelle** [comment]
Thank you very much @kcat! Keeping the `DeviceManager` did the trick.
