### ISSUE TITLE
_INCLUDE_DIRS vs _INCLUDE_DIR

### ISSUE THREAD

**Issue by karamellpelle** [kcat/alure#3]
Inconsistent naming: _. /CMakeLists.txt_ use `MPG123_INCLUDE_DIRS` but _./cmake/FindMPG123.cmake_ use `MPG123_INCLUDE_DIR`. ~`XXX_INCLUDE_DIRS` (with a `S`) seems to be the convention, so I assume _FindMPG123.cmake_ should be modified.~ [I'm not sure which to use](https://cmake.org/pipermail/cmake/2006-October/011502.html) . 

My mpg123 is installed (via homebrew) in _/usr/local_ and _/usr/local/include_ is not given to the compiler since _./CMakeLists.txt_ use the variable with `S` and this is empty. This gives a compilation error.

**Comment by kcat** [comment]
Fixed in commit 167737ff43763c9baa6c779e005a58d81bf5f0d9
