### ISSUE TITLE
Let CMakeLists.txt export ALURE_LIBRARIES and ALURE_INCLUDE_DIRS

### ISSUE THREAD

**Issue by karamellpelle** [kcat/alure#4]
Hello! Is it possible to let _./CMakeLists.txt_ export `ALURE_LIBRARIES` and `ALURE_INCLUDE_DIRS`? I have alure as a git submodule and use it as a cmake submodule (`add_subdirectory( alure )`). In my top _CMakeLists.txt_ it would be nice to use these variables and not hardcode the paths and link libraries by hand.

For example, the submodule glfw of mine makes this possible:

    set(GLFW_LIBRARIES ${glfw_LIBRARIES} CACHE STRING "Dependencies of GLFW")

**Comment by karamellpelle** [comment]
I suppose this at the end will do the job:

    set(ALURE_LIBRARIES alure2 ${alure_libs} CACHE STRING "Dependencies of ALURE")

But better: Add all include and link dependencies of target `alure2` with `target_include_directories()` and `target_link_libraries()`. And for each optional package dependency found (like mpg123), add it to `alure2`. Now I have to find these optional packages (i.e. mpg123) by myself again, and then add them to my target.

**Comment by kcat** [comment]
> But better: Add all include and link dependencies of target ```alure2``` with ```target_include_directories()``` and ```target_link_libraries()```. And for each optional package dependency found (like mpg123), add it to ```alure2```.

This should be the case now. It should also work for ```alure2_s``` (for static linking). Is there anything else it should do to "expose" the ```alure2``` and ```alure2_s``` targets for whatever includes this CMakeLists.txt?

**Comment by karamellpelle** [comment]
I'm not sure what else the _CMakeLists.txt_ should do; I'm not very into CMake right now. 

However, using Alure with [the newest commit](https://github.com/kcat/alure/commit/e8ae3d3d134c12c9b6aace5e07885807f0bf6024) as a submodule works well. Thank you!
