### ISSUE TITLE
kcat.strangesoft.net site is gone

### ISSUE THREAD

**Issue by chenrui333** [kcat/alure#47]
👋  just to raise the issue in here since the old artifacts are not accessible either.

**Comment by McSinyx** [comment]
IIRC alure2 has never been documented anywhere, so it's probably irrelevant to the mentioned site.

**Comment by chenrui333** [comment]
@McSinyx I am sorry, I dont quite understand what you referred to. I think the site along with the releases artifacts are all gone.

**Comment by McSinyx** [comment]
What I mean was that this repository is alure 2, which is the C++ rewrite of alure 1.x (the one on the site) with a different API.

**Comment by chenrui333** [comment]
I see, that makes sense. So it is understandable the site got removed?

**Comment by McSinyx** [comment]
I don't think so, since the openal-soft's docs were also hosted over there; just wanted to point out that there is no alure2 resource on that site.

**Comment by kcat** [comment]
The strangesoft.net domain URL expired. I still have everything on the data host server, and will check with the server admin to see if there's another way to publicly access it. openal-soft.org is using the same host and is unaffected.

**Comment by chenrui333** [comment]
> The strangesoft.net domain URL expired. I still have everything on the data host server, and will check with the server admin to see if there's another way to publicly access it. openal-soft.org is using the same host and is unaffected.

that sounds pretty good, let me switch to `openal-soft.org` (at least in this way, alure1 is rebuildable). Thanks @kcat!

**Comment by chenrui333** [comment]
hmm, I was mistaken, yeah, we still need `kcat.strangesoft.net` or any site to allow the allure1 artifacts publicly accessible.

**Comment by kcat** [comment]
The page can be accessed through https://kcat.tomasu.net/alure.html now. They're asking way too much to give the strangesoft.net domain back, so it's unlikely that will be back any time soon, unfortunately.

**Comment by chenrui333** [comment]
yeah, I dont care which domain pointing to. In fact, I think `.dev` domain might be cheap ones.

**Comment by chenrui333** [comment]
Close the issue for now as the site is back. I have filed a PR to revert my change on the homebrew side.
