### ISSUE TITLE
Build errors on macOS Sierra (std::array and constexpr)

### ISSUE THREAD

**Issue by karamellpelle** [kcat/alure#5]
The current code [does not build](https://github.com/kcat/alure/files/674702/issue.txt) on macOS Sierra. It is very easy to fix, however:

  * Add `#include <array>` to the includes in _include/AL/alure2.h_.
  * Remove `constexpr` from the function `Vector3::getLength()` in _include/AL/alure2.h_ (`std::sqrt()` is not a compile time function (constexpr)).

**Comment by kcat** [comment]
It's building now on macOS using XCode8. Have the errors been fixed on your end too?

**Comment by karamellpelle** [comment]
Sorry for very late answer! I've been away from programming for a long time. 

Alure with the newest commit [e8ae3d3d](https://github.com/kcat/alure/commit/e8ae3d3d134c12c9b6aace5e07885807f0bf6024) builds on my macOS High Sierra with XCode 9.1. The examples are working.
