### ISSUE TITLE
C++14 only?

### ISSUE THREAD

**Issue by soulslicer** [kcat/alure#9]
Does this only support compilers which support c++14?

**Comment by kcat** [comment]
It should only require C++11. Are you getting an error? What compiler and compiler version?

**Comment by McSinyx** [comment]
I saw 50f92fe528e77da82197fd947d1cf9b0a82a0c7d made the requirements to C++14, but the current codebase does not use any C++14 feature I think.  Is there a future plan to, say, use `remove_reference_t` and `enable_if_t` instead of the aliases in `alure2-aliases.h`?

**Comment by kcat** [comment]
I more did that just so I (and any future contributor) knows C++14 is fine now. Not sure when I'll get around to doing anything with it, but it's okay to use.
